select * from DSSV where HoVaTen=N'Nguyễn Hữu Quỳnh'

create nonclustered index [IX_DSSV_HVTen] on DSSV
([HoVaTen] ASC)
With (PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, SORT_IN_TEMPDB=OFF,
IGNORE_DUP_KEY=OFF,DROP_EXISTING=OFF, ONLINE=OFF,
ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY]

CREATE CLUSTERED INDEX [IX_DanhSachSV_HoVaTen] on DSSV
([HoVaTen] ASC)
With (PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF,
SORT_IN_TEMPDB=OFF, IGNORE_DUP_KEY=OFF,DROP_EXISTING=OFF,
ONLINE=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY]

 CREATE NONCLUSTERED INDEX [IX_DanhSachSV_Ten_HoDem] on DSSV
([Ten] ASC) INCLUDE (HoDem)
With (PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF,
SORT_IN_TEMPDB=OFF, IGNORE_DUP_KEY=OFF,DROP_EXISTING=OFF,
ONLINE=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON) ON [PRIMARY]

select HoDem, Ten from DSSV where Ten=N'Anh'


 delete from DSSV where MaSV in (select MaSV from DSSV group by MaSV having count(MaSV)>1)